name: Windows
on: workflow_dispatch
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-2022
    steps:
      - name: Checkout g3log
        uses: actions/checkout@v4
        with:
          repository: KjellKod/g3log
          ref: 2.3
          path: g3log
      - name: Init MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build g3log
        run: |
          cd g3log
          mkdir build
          cd build
          cmake ../ -DUSE_DYNAMIC_LOGGING_LEVELS=ON -DENABLE_VECTORED_EXCEPTIONHANDLING=OFF -DENABLE_FATAL_SIGNALHANDLING=OFF
          cmake --build . --config Debug
          cmake --install . --config Debug --prefix install/Debug
          cmake --build . --config Release
          cmake --install . --config Release --prefix install/Release
      - name: Generate zip
        run: |
          echo ${{ github.sha }} > Release.txt
          Compress-Archive -Path ./g3log/build/install/*,./Release.txt -DestinationPath g3log.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: g3log.zip